### ISSUE TITLE
build breaks

### ISSUE THREAD

**Issue by geebinge** [microsoft/do-client#192]
Hi, 

if I try the step `python3 build/build.py --project plugin-apt --package-for deb` from [delivery-optimization-client](https://github.com/microsoft/do-client?tab=readme-ov-file#delivery-optimization-client) i get 

```
script_path=/home/gerhard/test-x509/do-client/build
Starting Build for project: plugin-apt
Target OS: Linux
Flavor: linux-debug
Config: debug
Subproject: plugin-apt
CMake Target: all
CMake Generator: Ninja
Clean: False
Source Path: /home/gerhard/test-x509/do-client
Build Path: /tmp/build-deliveryoptimization-plugin-apt/linux-debug
Running command cmake /home/gerhard/test-x509/do-client -G Ninja -DCMAKE_BUILD_TYPE=Debug -DDO_BUILD_TIMESTAMP=20240730.155226 -DDO_INCLUDE_PLUGINS=TRUE.
-- DO Platform: Linux
-- DO Interface: REST
-- DO Client: Agent
CMake Warning at CMakeLists.txt:96 (message):
  /lib is a symlink and /include does not exist.  Updating CMAKE_PREFIX_PATH
  to /usr.


-- Using builder name: DU
-- NOTE: Please modify builder name if modifying project source
-- Build timestamp found: 20240730.155226
-- Including subproject plugins
-- Packaging for DEB
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build-deliveryoptimization-plugin-apt/linux-debug
Executing: cmake --build /tmp/build-deliveryoptimization-plugin-apt/linux-debug --target all
Running command cmake --build /tmp/build-deliveryoptimization-plugin-apt/linux-debug --target all.
[3/4] Building CXX object plugins/linux-apt/CMakeFiles/deliveryoptimization-plugin-apt.dir/main.cpp.o
FAILED: plugins/linux-apt/CMakeFiles/deliveryoptimization-plugin-apt.dir/main.cpp.o
/usr/bin/c++  -DDO_CLIENT_AGENT=1 -DDO_INTERFACE_REST=1 -DDO_PLATFORM_LINUX=1 -DDO_PLUGIN_APT_CACHE_PATH=\"/var/cache/deliveryoptimization-plugin-apt\" -DDO_PLUGIN_APT_LOG_PATH=\"/tmp/deliveryoptimization-plugin-apt.log\" -I/home/gerhard/test-x509/do-client/common/lib-doversion -isystem /usr/include/deliveryoptimization -isystem /usr/include/uuid -Wall -fPIE -pie -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -Wreturn-local-addr -fmerge-all-constants -g -DDEBUG -fPIE   -std=c++17 -MD -MT plugins/linux-apt/CMakeFiles/deliveryoptimization-plugin-apt.dir/main.cpp.o -MF plugins/linux-apt/CMakeFiles/deliveryoptimization-plugin-apt.dir/main.cpp.o.d -o plugins/linux-apt/CMakeFiles/deliveryoptimization-plugin-apt.dir/main.cpp.o -c /home/gerhard/test-x509/do-client/plugins/linux-apt/main.cpp
/home/gerhard/test-x509/do-client/plugins/linux-apt/main.cpp: In function ‘DownloadResult SimpleDownload(const string&, const string&)’:
/home/gerhard/test-x509/do-client/plugins/linux-apt/main.cpp:196:73: error: conversion from ‘void’ to non-scalar type ‘std::error_code’ requested
  196 |         std::error_code errorCode = msdo::download::download_url_to_path(url, tempPath);
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
Running cmake --build /tmp/build-deliveryoptimization-plugin-apt/linux-debug --target all failed. Rethrowing exception
Traceback (most recent call last):
  File "build/build.py", line 761, in <module>
    main()
  File "build/build.py", line 31, in main
    build.run()
  File "build/build.py", line 460, in run
    super().run()
  File "build/build.py", line 264, in run
    self.build()
  File "build/build.py", line 382, in build
    run_command(build_command)
  File "build/build.py", line 724, in run_command
    _check_call(command)
  File "build/build.py", line 748, in _check_call
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/tmp/build-deliveryoptimization-plugin-apt/linux-debug', '--target', 'all']' returned non-zero exit status 1.
`

I have tested this with main and develop 

I use Ubuntu 20.04

**Comment by shishirb-MSFT** [comment]
I'm unable to reproduce in 20.04, develop branch. You probably have an incompatible version of the DO SDK installed. See the steps to install the SDK in the [README.md](https://github.com/microsoft/do-client/blob/develop/README.md).

Curious why you are trying to build and use the APT plugin. Are you using Microsoft Connected Cache in your environment?

**Comment by shishirb-MSFT** [comment]
No response. Closing.
